import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import ts from "typescript";
const source = readFileSync(new URL("./src/itinerary.ts", import.meta.url), "utf8");
const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext } }).outputText;
const { getItineraryDays, serializeItinerary, emptyItineraryDay } = await import(`data:text/javascript;base64,${Buffer.from(compiled).toString("base64")}`);
const legacy = ["DAY 1 - Travel: Full original text.\n\nAnother paragraph.", "Visit the grassland", "DAY 2 - Return: More text."];
const migrated = getItineraryDays({ itinerary: legacy });
assert.equal(migrated.length, 2);
assert.equal(migrated[0].activities.length, 2);
assert.deepEqual(migrated.flatMap(day => day.activities.map(activity => activity.description)), legacy);
assert.equal(getItineraryDays({ itinerary: ["Meet", "Walk", "Return"] }).length, 1);
const days = [{ activities: [{ title: "Travel", description: "First paragraph.\n\nSecond paragraph." }, { title: "Explore", description: "Full details" }], overnight: "Dinsho campsite", meals: "Lunch and dinner" }, emptyItineraryDay()];
const saved = JSON.parse(JSON.stringify({ itineraryDays: days, itinerary: serializeItinerary(days) }));
assert.deepEqual(getItineraryDays(saved), days);
assert.match(saved.itinerary[0], /First paragraph\.\n\nSecond paragraph\./);
assert.match(saved.itinerary[0], /Overnight: Dinsho campsite/);
assert.match(saved.itinerary[0], /Meals: Lunch and dinner/);
assert.equal(getItineraryDays({ itinerary: [] })[0].activities.length, 1);
console.log("Passed itinerary compatibility, multi-activity, paragraph preservation and storage round-trip checks.");
